import type { NavigationTree } from "@/@types/navigation"
import {
  Box,
  Calendar,
  Chart2,
  Cut,
  DocumentFilter,
  DocumentText,
  Educare,
  Home,
  Profile2User,
  RulerPen,
  Scan,
  Setting3,
  Wallet1,
} from "iconsax-reactjs"
import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from "@/constants/navigation.constant"

const migiosNavigationConfig: NavigationTree[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: () => <Home variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/schedule",
    title: "Schedule",
    icon: () => <Calendar variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "",
    title: "Attendance",
    icon: () => <Scan variant="Bulk" />,
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        path: "/attendance/checkin",
        title: "Check in",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        path: "/attendance/checkout",
        title: "Check out",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        path: "/attendance/history",
        title: "History",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    path: "/class/schedule",
    title: "Class",
    icon: () => <Educare variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/members",
    title: "Members",
    icon: () => <Profile2User variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/cutting-sessions",
    title: "Cutting Session",
    icon: () => <Cut variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/measurement",
    title: "Measurement",
    icon: () => <RulerPen variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "",
    title: "Masters",
    icon: () => <Wallet1 variant="Bulk" />,
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        path: "/sales",
        title: "Sales",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Chart2 variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/packages/membership",
        title: "Packages",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <DocumentFilter variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/products",
        title: "Products",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Box variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/finance/rekening",
        title: "Finance",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Wallet1 variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/employee",
        title: "Employee",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Profile2User variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/reports",
        title: "Reports",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <DocumentText variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/settings",
        title: "Settings",
        type: NAV_ITEM_TYPE_COLLAPSE,
        icon: () => <Setting3 variant="Bulk" />,
        authority: [],
        subMenu: [
          {
            path: "/settings/roles-permissions",
            title: "Roles & Permissions",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/gym/about",
            title: "Gym",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/others/commission",
            title: "Others",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/log-activity",
            title: "Log activity",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
    ],
  },
]

export default migiosNavigationConfig
