import type { NavigationTree } from "@/@types/navigation"
import {
  Box,
  Calendar,
  Chart2,
  Cut,
  DocumentFilter,
  DocumentText,
  Home,
  People,
  Profile2User,
  RulerPen,
  Scan,
  Setting3,
  Wallet1,
} from "iconsax-reactjs"
import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from "@/constants/navigation.constant"

const migiosNavigationConfig: NavigationTree[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: () => <Home variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/schedule",
    title: "Jadwal",
    icon: () => <Calendar variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "",
    title: "Absensi",
    icon: () => <Scan variant="Bulk" />,
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        path: "/attendance/checkin",
        title: "Check In",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        path: "/attendance/checkout",
        title: "Check Out",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        path: "/attendance/history",
        title: "Riwayat",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    path: "/class/list",
    title: "Kelas",
    icon: () => <People variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/members",
    title: "Anggota",
    icon: () => <Profile2User variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/cutting-sessions",
    title: "Potong Sesi",
    icon: () => <Cut variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "/measurement",
    title: "Pengukuran",
    icon: () => <RulerPen variant="Bulk" />,
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    path: "",
    title: "Master",
    icon: () => <Wallet1 variant="Bulk" />,
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        path: "/sales",
        title: "Penjualan",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Chart2 variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/packages/membership",
        title: "Paket",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <DocumentFilter variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/products",
        title: "Produk",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Box variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/finance/rekening",
        title: "Keuangan",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Wallet1 variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/employee",
        title: "Karyawan",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <Profile2User variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/reports",
        title: "Laporan",
        type: NAV_ITEM_TYPE_ITEM,
        icon: () => <DocumentText variant="Bulk" />,
        authority: [],
        subMenu: [],
      },
      {
        path: "/settings",
        title: "Pengaturan",
        type: NAV_ITEM_TYPE_COLLAPSE,
        icon: () => <Setting3 variant="Bulk" />,
        authority: [],
        subMenu: [
          {
            path: "/settings/roles-permissions",
            title: "Role & Hak Akses",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/gym/about",
            title: "Gym",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/others/sales",
            title: "Lainnya",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            path: "/settings/log-activity",
            title: "Log Aktivitas",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
    ],
  },
]

export default migiosNavigationConfig
