import {
  Bell,
  Bug,
  Construction,
  FileX,
  HelpCircle,
  LayoutDashboard,
  ListTodo,
  Lock,
  MessagesSquare,
  Monitor,
  Package,
  Palette,
  ServerOff,
  Settings,
  ShieldCheck,
  UserCog,
  UserX,
  Users,
  Wrench,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

const navigationIcon: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  tasks: ListTodo,
  apps: Package,
  chats: MessagesSquare,
  users: Users,
  auth: ShieldCheck,
  errors: Bug,
  unauthorized: Lock,
  forbidden: UserX,
  notFound: FileX,
  serverError: ServerOff,
  maintenance: Construction,
  settings: Settings,
  profile: UserCog,
  account: Wrench,
  appearance: Palette,
  notifications: Bell,
  display: Monitor,
  helpCenter: HelpCircle,
}

export default navigationIcon
